void main() {
  // try {
  //   var result = 4 ~/ 0;
  //   print(result);
  // } on UnsupportedError {
  //   print('Can not divide by zero');
  // }

  // try catch
  // try {
  //   var result = 4 ~/ 0;
  //   print(result);
  // } catch (e) {
  //   print('Can not be divde by 0');
  // }

  // try {
  //   var result = 4 ~/ 0;
  //   print(result);
  // } on IntegerDivisionByZeroException catch (e) {
  //   print('Can\'t done');
  // }

  //finally keyword
  // try {
  //   var result = 4 ~/ 2;
  //   print(result);
  // } on IntegerDivisionByZeroException catch (e) {
  //   print('Can\'t done');
  // } finally {
  //   print('Finally Always Executes');
  // }
}
